export type ProjectCategory = "Mobile" | "UI/UX" | "Frontend" | "Full Stack" | "Web3";

export type Project = {
  slug: string;
  title: string;
  category: ProjectCategory;
  description: string;
  longDescription: string;
  tech: string[];
  year: string;
  role: string;
  image: string;
  images: string[];
  color: string;
  featured?: boolean;
  link?: string;
  challenge: string;
  goal: string;
  process: string[];
  solution: string;
  result: string;
  responsibilities: string[];
};

export const projects: Project[] = [
  {
    slug: "mobile-bengkelin",
    title: "Mobile Bengkelin",
    category: "UI/UX",
    description: "Mobile workshop service app — streamlined booking, history, and service management.",
    longDescription: "UI/UX exploration for on-demand workshop services, designed to make complex service flows feel effortless on mobile.",
    tech: ["Figma", "UI/UX"],
    year: "2024",
    role: "UI/UX Designer",
    image: "/porto/lap-on.png",
    images: ["/porto/lap-on.png", "/porto/pecel.png"],
    color: "#0F3D2E",
    featured: true,
    challenge: "Workshop booking to handover involves multiple steps that must remain simple on small screens.",
    goal: "Reduce booking friction to three clear steps with transparent status tracking.",
    process: ["User flow mapping", "Low-fidelity wireframes", "High-fidelity UI", "Interactive prototype"],
    solution: "Three-step booking flow with diagnostic cards and real-time service status.",
    result: "Developer-ready design prepared for Flutter implementation.",
    responsibilities: ["User flow and UI design", "Prototyping"],
  },
  {
    slug: "the-paranola",
    title: "The Paranola — Fashion Platform",
    category: "UI/UX",
    description: "Contemporary fashion platform built around 'Wear the trend, own the moment' — bold, clean, and premium.",
    longDescription: "A confident, inclusive fashion identity that balances contemporary trends with timeless simplicity, brought to life through warm, optimistic visuals and editorial clarity.",
    tech: ["Figma", "UI/UX", "Design System"],
    year: "2024",
    role: "UI/UX Designer",
    image: "/porto/paranola.png",
    images: ["/porto/paranola.png"],
    color: "#C9A86A",
    featured: true,
    challenge: "Communicate trend-forward energy and premium quality without sacrificing clarity.",
    goal: "Craft a fashion experience that feels aspirational, accessible, and unmistakably premium.",
    process: ["Moodboarding and warm palette definition", "Minimal premium layout system", "Hero storytelling — 'Wear the trend'", "Calls to action and social proof"],
    solution: "Warm yellow hero, 'Simple Made' and 'New Arrivals' storytelling, brand wall featuring Lacoste, Levi's, Amazon, H&M, Obey, and Shopify, and refined editorial spacing.",
    result: "Cohesive fashion design system ready for e-commerce implementation.",
    responsibilities: ["Art direction and UI/UX", "Color and typography", "Interactive prototype"],
  },
  {
    slug: "seedrym",
    title: "Seedrym — Web3 Farmland Ownership on Solana",
    category: "Web3",
    description: "Decentralized platform enabling fractional farmland ownership on Solana — starting from $0.59 with on-chain yield.",
    longDescription: "Investors earn real harvest yield and track ownership transparently on-chain. Hero narrative: 'Harvest yield rights, finally accessible.'",
    tech: ["Next.js", "Rust", "Anchor", "Solana"],
    year: "2024",
    role: "Frontend Developer & Blockchain Integrator",
    image: "/porto/seedrym.png",
    images: ["/porto/seedrym.png"],
    color: "#0F3D2E",
    featured: true,
    challenge: "Explain structured land ownership and on-chain yield without overwhelming newcomers with jargon.",
    goal: "Convert curious visitors into $0.59 farmland investors through clear, trustworthy storytelling.",
    process: ["Narrative and tokenomics design", "Hero and batch showcase", "On-chain ownership tracker"],
    solution: "Dark-green hero with 'Harvest yield' messaging, batch cards, and legal, Solana, and auto-yield verification.",
    result: "Web3 concept ready for investor presentation and further development.",
    responsibilities: ["Frontend development", "Anchor program integration"],
  },
  {
    slug: "gelora-bookapp",
    title: "Gelora — Space for Sport",
    category: "Mobile",
    description: "Unified sports platform for field booking, equipment rental, and marketplace — seamless discovery to checkout.",
    longDescription: "End-to-end mobile platform that consolidates field booking, sports equipment rental, and marketplace commerce into a single, intuitive experience.",
    tech: ["Flutter", "Dart", "REST API"],
    year: "2024",
    role: "Mobile Developer (Flutter) — Slicing & Integration",
    image: "/porto/gelora.png",
    images: ["/porto/gelora.png", "/porto/lap-on.png"],
    color: "#0F3D2E",
    featured: true,
    link: "https://github.com/Yogaprtamaa/gelora-bookapp-mobile",
    challenge: "Field bookings and equipment rentals were fragmented across chats and offline channels, with no unified catalog, schedule, or checkout.",
    goal: "Deliver a single mobile flow that unifies booking, rental, and commerce with fast, visual, and mobile-first usability.",
    process: ["Pixel-perfect slicing from Figma to Flutter", "State management and API integration", "Booking flow and marketplace cart", "Device testing and performance optimization"],
    solution: "Flutter app featuring popular field categories, promotions, transaction history, and profile — with a dark header, rounded cards, bottom navigation, and precise slicing.",
    result: "Six core screens sliced and integrated, ready for backend connection. APK available via GitHub.",
    responsibilities: ["Pixel-perfect Flutter slicing", "API integration", "Responsive performance"],
  },
  {
    slug: "bisindo-mobile",
    title: "BISINDO Mobile — Realtime Sign Language Detector",
    category: "Mobile",
    description: "Real-time Indonesian Sign Language (BISINDO) detection powered by Flutter and Computer Vision.",
    longDescription: "On-device sign language detection that overlays bounding boxes, labels, and confidence scores on the camera preview and translates them into text in real time.",
    tech: ["Flutter", "TFLite", "Computer Vision", "Camera"],
    year: "2024",
    role: "Mobile Developer (Flutter) — Computer Vision Integration",
    image: "/porto/bisindo.png",
    images: ["/porto/bisindo.png", "/porto/bisindo-2.png", "/porto/bisindo-3.png"],
    color: "#0F5D3A",
    featured: true,
    link: "https://github.com/Yogaprtamaa/bisindo-mobile",
    challenge: "Sign language detection requires a lightweight model, stable camera preview, and non-intrusive overlay.",
    goal: "Achieve accurate, real-time BISINDO alphabet detection with confidence scoring directly on the camera feed.",
    process: ["Model and dataset research for BISINDO", "TFLite and camera pipeline integration", "Bounding box, label, and score overlay", "FPS and accuracy optimization"],
    solution: "Camera → inference → overlay pipeline with an educational ABJAD BISINDO reference — including IDLE and MOCK modes for demonstration.",
    result: "Real-time detection running smoothly on device, ready for demo and further iteration.",
    responsibilities: ["Flutter and TFLite integration", "Camera and overlay engineering", "Real-time UX"],
  },
  {
    slug: "school-management-mobile",
    title: "School Management Mobile App",
    category: "Mobile",
    description: "Multi-tenant Flutter application for end-to-end school management across roles and institutions.",
    longDescription: "Mobile extension of a school management platform supporting multi-tenant deployment and role-based access for students, teachers, staff, and administrators.",
    tech: ["Flutter", "Dart", "Multi-tenant", "Role-based Access"],
    year: "2024",
    role: "Mobile Developer (Flutter)",
    image: "/porto/schoolmanagement.png",
    images: ["/porto/schoolmanagement.png", "/porto/schoolmanagement-2.png"],
    color: "#1E3A5F",
    featured: true,
    link: "https://github.com/Yogaprtamaa/school-management-mobile",
    challenge: "A single application must serve four distinct roles with isolated data and permissions per school.",
    goal: "Ship one Flutter codebase that scales across schools while keeping role-specific experiences lightweight and clear.",
    process: ["Multi-tenant and role architecture", "Dashboard and schedule slicing", "School feed and profile modules", "Cross-role testing"],
    solution: "Explore Dashboard, My Schedule, Tap In/Out, School Feed, and Profile — with orange-purple role coding for quick recognition.",
    result: "Production-ready APK supporting all four roles across multiple schools from a single codebase.",
    responsibilities: ["Multi-tenant architecture", "UI slicing", "Role management"],
  },
  {
    slug: "compro-pkumi-istiqlal",
    title: "Company Profile — PKUMI Masjid Istiqlal",
    category: "Frontend",
    description: "Institutional company profile for PKUMI Masjid Istiqlal — formal, modern, and trustworthy.",
    longDescription: "Company profile anchored by the hero 'Pendidikan Kader Ulama Masjid Istiqlal' alongside the iconic Istiqlal Mosque imagery.",
    tech: ["Next.js"],
    year: "2024",
    role: "Frontend Developer",
    image: "/porto/compro-pkumi.png",
    images: ["/porto/compro-pkumi.png"],
    color: "#0B4D3E",
    featured: true,
    challenge: "Institutional image must convey formality, modernity, and trustworthiness.",
    goal: "Build a company profile that inspires confidence in prospective students and the public.",
    process: ["Hero and navigation design", "Education overview", "Call-to-action strategy"],
    solution: "White-green hero with a prominent 'Daftar Sekarang' call to action and Istiqlal architectural photography.",
    result: "Live company profile representing the institution.",
    responsibilities: ["Next.js development", "Responsive implementation"],
  },
  {
    slug: "website-booking-umkm",
    title: "Website Booking — For UMKM",
    category: "UI/UX",
    description: "Conversion-focused booking website for MSMEs — approachable, fast, and trustworthy.",
    longDescription: "Booking experience tailored for micro, small, and medium enterprises that prioritizes usability for non-technical users.",
    tech: ["Figma", "UI/UX"],
    year: "2024",
    role: "UI/UX Designer",
    image: "/porto/pijet.png",
    images: ["/porto/pijet.png"],
    color: "#E8A0BF",
    challenge: "MSME customers need a booking experience that feels familiar, not intimidating.",
    goal: "Create a welcoming, high-converting booking website built for trust and speed.",
    process: ["MSME user research", "Information architecture", "High-fidelity UI", "Usability testing"],
    solution: "Category hero, intuitive calendar, and minimal checkout optimized for conversion.",
    result: "Validated booking concept ready for development.",
    responsibilities: ["UI/UX design and research"],
  },
  {
    slug: "website-logictic",
    title: "Website Logistic",
    category: "UI/UX",
    description: "Logistics management website — shipment tracking, operations dashboard, and analytics.",
    longDescription: "Logistics exploration focused on making complex shipment data instantly understandable for operations teams and end users.",
    tech: ["Figma", "UI/UX"],
    year: "2024",
    role: "UI/UX Designer",
    image: "/porto/logistic.png",
    images: ["/porto/logistic.png"],
    color: "#1E3A5F",
    challenge: "Tracking complexity must be simplified without losing operational detail.",
    goal: "Deliver a logistics dashboard that is readable at a glance and actionable in seconds.",
    process: ["Operational flow analysis", "Dashboard UI design", "User testing"],
    solution: "Status cards, delivery timeline, and smart filters for rapid oversight.",
    result: "Exploratory logistics system with clear information hierarchy.",
    responsibilities: ["UI design and flow"],
  },
  {
    slug: "e-commerse-umkm",
    title: "E-Commerce for UMKM",
    category: "UI/UX",
    description: "Curated e-commerce experience for MSMEs — catalog, cart, and checkout with quality curation.",
    longDescription: "A thoughtfully curated online marketplace for MSMEs where product quality is safeguarded through admin oversight.",
    tech: ["Figma", "UI/UX"],
    year: "2024",
    role: "UI/UX Designer",
    image: "/porto/ecommerse-forumkm.png",
    images: ["/porto/ecommerse-forumkm.png"],
    color: "#FF4D1A",
    challenge: "Generic marketplaces lack curation — MSMEs need a trusted, well-merchandised storefront.",
    goal: "Create a browsable catalog organized by Food, Beverage, Fashion, and Daily Essentials.",
    process: ["Catalog and category strategy", "Product card system", "Admin curation workflow"],
    solution: "Category grid with '4,583 products' badges and a dedicated For UMKM narrative that communicates quality control.",
    result: "Presentation-ready e-commerce concept for MSME stakeholders.",
    responsibilities: ["Catalog and card system", "UX strategy"],
  },
  {
    slug: "pmb-pku-admin",
    title: "PMB-PKU Admin Dashboard",
    category: "Frontend",
    description: "Administration dashboard for new student admissions — built with Next.js and Laravel Sanctum.",
    longDescription: "Comprehensive admin console for managing applicant documents, interview scheduling, selection stages, and graduation status with filtering and reporting.",
    tech: ["Next.js", "Laravel Sanctum", "PostgreSQL"],
    year: "2024",
    role: "Frontend Developer",
    image: "/porto/pmbadmin.png",
    images: ["/porto/pmbadmin.png", "/porto/pmb-fe.png"],
    color: "#1D2A4D",
    featured: false,
    link: undefined,
    challenge: "High applicant volume requires staged verification with clear status visibility.",
    goal: "Empower administrators to monitor registration, interviews, and graduation outcomes efficiently.",
    process: ["Admin information architecture", "Dashboard component system", "Sanctum integration", "Export and reporting"],
    solution: "Status cards (10/9/0/1/1/1), advanced filters, and an active admission period panel — minimal and highly legible.",
    result: "Production admin dashboard deployed under institutional copyright.",
    responsibilities: ["Next.js frontend", "API integration"],
  },
  {
    slug: "pos-bussines",
    title: "POS Business — Next.js & Supabase",
    category: "Full Stack",
    description: "Point-of-sale system for culinary businesses — fast menu selection, automated totals, and daily recaps.",
    longDescription: "A streamlined POS for food and beverage operations: select items, adjust quantities, and view fees and margins in real time.",
    tech: ["Next.js", "Supabase", "PostgreSQL"],
    year: "2024",
    role: "Full Stack Developer",
    image: "/porto/pecel.png",
    images: ["/porto/pecel.png"],
    color: "#0F3D2E",
    challenge: "Cashier workflows demand speed, accuracy, and instant reconciliation.",
    goal: "Deliver a POS that is lightning-fast at the counter with clear daily revenue insights.",
    process: ["Menu and inventory modeling", "Cart and fee logic", "Daily recap and reporting"],
    solution: "Menu grid for chicken and tofu, summary panel showing Rp 975,100 with 29.7% margin, and a New Order action.",
    result: "Operational POS deployed for daily service.",
    responsibilities: ["Full-stack development", "Supabase integration"],
  },
  {
    slug: "pmb-pku-istiqlal",
    title: "PMB PKU Istiqlal — Student Portal",
    category: "Frontend",
    description: "Student-facing admission portal for PKU Masjid Istiqlal — transparent progress from documents to graduation.",
    longDescription: "Students track their journey through Profile, Documents, Interview, and Announcement stages — exemplified by the 'Congratulations! You Passed the Document Stage' state.",
    tech: ["Next.js", "Laravel Sanctum"],
    year: "2024",
    role: "Frontend Developer",
    image: "/porto/pmb-fe.png",
    images: ["/porto/pmb-fe.png", "/porto/compro-pkumi.png"],
    color: "#0F3D2E",
    challenge: "Selection status must be transparent and guide students to their next step without anxiety.",
    goal: "Create a calm, reassuring portal with unmistakable progress and next actions.",
    process: ["Status journey mapping", "Announcement card design", "Interview scheduling flow"],
    solution: "Four-step stepper with a green 'Passed Document Stage' card, interview schedule, and WhatsApp contact.",
    result: "Live student portal under institutional copyright.",
    responsibilities: ["Frontend development", "Status UX"],
  },
  {
    slug: "portal-pkumi-admin",
    title: "Portal PKUMI — Admin Dashboard",
    category: "Frontend",
    description: "Content management dashboard for PKUMI's knowledge portal — 1,250 articles and editorial workflow.",
    longDescription: "Manage knowledge articles, rubrics, categories, and users — with an overview of 1,250 total, 120 drafts, 85 in review, and 1,045 published, plus publication workflow.",
    tech: ["Next.js", "Laravel Sanctum"],
    year: "2024",
    role: "Frontend Developer",
    image: "/porto/adminportal.png",
    images: ["/porto/adminportal.png", "/porto/portal-pkumi.png"],
    color: "#1E2A4D",
    challenge: "A large knowledge base requires clear taxonomy and an efficient editorial workflow.",
    goal: "Make content management and growth tracking effortless for editors.",
    process: ["Taxonomy design", "Dashboard and analytics", "Publication workflow"],
    solution: "Khazanah Panel with growth indicators (+4.2%), archive filters, and report printing.",
    result: "Active admin portal for PKUMI editorial operations.",
    responsibilities: ["Frontend and dashboard development"],
  },
  {
    slug: "portal-pkumi",
    title: "Portal PKUMI — Public Knowledge Portal",
    category: "Frontend",
    description: "Public knowledge portal for PKUMI — curated rubrics including Theology, Fiqh, and Hadith.",
    longDescription: "A reading experience for the public to explore curated knowledge: filter by All/News, article cards, and search.",
    tech: ["Next.js", "Laravel"],
    year: "2024",
    role: "Frontend Developer",
    image: "/porto/portal-pkumi.png",
    images: ["/porto/portal-pkumi.png"],
    color: "#0F3D2E",
    challenge: "Hundreds of articles require rubric navigation that never overwhelms the reader.",
    goal: "Enable comfortable, curiosity-driven exploration of Islamic knowledge.",
    process: ["Rubric architecture", "Article card system", "Search and filtering"],
    solution: "Rubric chips with a three-card grid (News, Theology, Medicine) and author, date, and view metadata.",
    result: "Live public portal with sustained readership.",
    responsibilities: ["Frontend development"],
  },
  {
    slug: "cv-ui-ux",
    title: "CV UI/UX — HTML & Bootstrap",
    category: "Frontend",
    description: "Interactive designer resume — concise profile, contact, and portfolio at a glance.",
    longDescription: "A single-page resume featuring a portrait at the Google wall, contact details, and a distilled UI/UX narrative.",
    tech: ["HTML", "Bootstrap"],
    year: "2024",
    role: "Frontend Developer",
    image: "/porto/cv.png",
    images: ["/porto/cv.png"],
    color: "#6E6E73",
    challenge: "A resume must feel personal yet remain instantly scannable and professional.",
    goal: "Communicate expertise and personality within a ten-second scan.",
    process: ["Resume layout and hierarchy", "Typography and spacing", "Responsive refinement"],
    solution: "Icon sidebar with a circular portrait and a concise right-panel summary.",
    result: "Share-ready online CV optimized for recruiters.",
    responsibilities: ["HTML and CSS implementation"],
  },
  {
    slug: "compro-pkumi-istiqlal",
    title: "Company Profile — PKUMI Masjid Istiqlal",
    category: "Frontend",
    description: "Institutional company profile for PKUMI Masjid Istiqlal — formal, modern, and trustworthy.",
    longDescription: "Company profile anchored by the hero 'Pendidikan Kader Ulama Masjid Istiqlal' alongside the iconic Istiqlal Mosque imagery.",
    tech: ["Next.js"],
    year: "2024",
    role: "Frontend Developer",
    image: "/porto/compro-pkumi.png",
    images: ["/porto/compro-pkumi.png"],
    color: "#0B4D3E",
    featured: true,
    challenge: "Institutional image must convey formality, modernity, and trustworthiness.",
    goal: "Build a company profile that inspires confidence in prospective students and the public.",
    process: ["Hero and navigation design", "Education overview", "Call-to-action strategy"],
    solution: "White-green hero with a prominent 'Daftar Sekarang' call to action and Istiqlal architectural photography.",
    result: "Live company profile representing the institution.",
    responsibilities: ["Next.js development", "Responsive implementation"],
  },
  {
    slug: "qc-poisson-analytics",
    title: "QC Poisson Analytics Dashboard",
    category: "Frontend",
    description: "Poisson-based quality control analytics — machine components, probability forecasts, and defect trends.",
    longDescription: "Daily data input, next-batch prediction, average defects, and trend visualization for data-driven QC decisions.",
    tech: ["JavaScript", "Chart.js"],
    year: "2024",
    role: "Frontend Developer",
    image: "/porto/poison-qc.png",
    images: ["/porto/poison-qc.png"],
    color: "#1E3A5F",
    challenge: "Poisson defect data must be visualized for rapid quality control decisions.",
    goal: "Translate raw QC data into a clear narrative of what happened and what is likely next.",
    process: ["Poisson model integration", "Chart and table design", "Analytical UX"],
    solution: "History table, probability forecasts (20.2%, 12.3%, 25.8%), and dedicated Iron Plate insights.",
    result: "Decision-ready dashboard for the QC team.",
    responsibilities: ["Frontend engineering", "Data visualization"],
  },
  {
    slug: "landing-page-prodi",
    title: "Landing Page — Agribusiness Study Program",
    category: "Frontend",
    description: "Academic landing page for the Agribusiness Study Program — warm, credible, and inviting.",
    longDescription: "Program landing featuring a green header, paddy field hero, and a clear 'Learn More' journey.",
    tech: ["HTML", "Bootstrap"],
    year: "2024",
    role: "Frontend Developer",
    image: "/porto/prodi.png",
    images: ["/porto/prodi.png"],
    color: "#0B6B3A",
    challenge: "The study program needs a landing page that feels both academic and welcoming.",
    goal: "Project an academic image that is warm, credible, and enrollment-ready.",
    process: ["Hero storytelling", "Program navigation", "Conversion call to action"],
    solution: "Green header for Agribusiness Study Program with a serene paddy field hero and focused CTA.",
    result: "Live program landing page.",
    responsibilities: ["HTML and CSS development"],
  },
  {
    slug: "seedrym",
    title: "Seedrym — Web3 Farmland Ownership on Solana",
    category: "Web3",
    description: "Decentralized platform enabling fractional farmland ownership on Solana — starting from $0.59 with on-chain yield.",
    longDescription: "Investors earn real harvest yield and track ownership transparently on-chain. Hero narrative: 'Harvest yield rights, finally accessible.'",
    tech: ["Next.js", "Rust", "Anchor", "Solana"],
    year: "2024",
    role: "Frontend Developer & Blockchain Integrator",
    image: "/porto/seedrym.png",
    images: ["/porto/seedrym.png"],
    color: "#0F3D2E",
    featured: true,
    challenge: "Explain structured land ownership and on-chain yield without overwhelming newcomers with jargon.",
    goal: "Convert curious visitors into $0.59 farmland investors through clear, trustworthy storytelling.",
    process: ["Narrative and tokenomics design", "Hero and batch showcase", "On-chain ownership tracker"],
    solution: "Dark-green hero with 'Harvest yield' messaging, batch cards, and legal, Solana, and auto-yield verification.",
    result: "Web3 concept ready for investor presentation and further development.",
    responsibilities: ["Frontend development", "Anchor program integration"],
  },
  {
    slug: "sim-gakda-satpol-pp",
    title: "Sim-Gakda Satpol PP — Reporting System",
    category: "Frontend",
    description: "Reporting and command system for Satpol PP — vulnerability mapping and case management for East Kalimantan.",
    longDescription: "Map-based dashboard with central command levels, assessment results, and real-time activity for coordinated enforcement.",
    tech: ["Next.js", "Map Integration"],
    year: "2024",
    role: "Frontend Developer",
    image: "/porto/sim-gakda.png",
    images: ["/porto/sim-gakda.png"],
    color: "#1E3A5F",
    challenge: "Reports must be understood spatially and chronologically at once.",
    goal: "Combine map intelligence with a clear timeline for decisive command.",
    process: ["Map and geospatial layer design", "Report listing and verification flow", "Activity feed"],
    solution: "East Kalimantan vulnerability map with a verification pipeline and live activity panel.",
    result: "Active reporting system supporting field operations.",
    responsibilities: ["Next.js development", "Map integration"],
  },
  {
    slug: "zoya-cipta-erp",
    title: "Zoya Cipta ERP",
    category: "Full Stack",
    description: "Enterprise resource planning system for Zoya Cipta — inventory, sales, and financial operations.",
    longDescription: "Comprehensive ERP featuring 104 pcs in stock, 42 pending, Rp 3,894,000 revenue, sales trends, and quick actions.",
    tech: ["Next.js", "PostgreSQL"],
    year: "2024",
    role: "Full Stack Developer",
    image: "/porto/zoya.png",
    images: ["/porto/zoya.png"],
    color: "#1E3A5F",
    challenge: "ERP systems often become labyrinthine — this one needed to stay radically simple.",
    goal: "Answer 'what needs action today' at a glance for operations and finance.",
    process: ["Inventory module design", "Sales trend visualization", "Quick-action workflows"],
    solution: "Metric cards, 'Sales Trend' chart, and a Quick Actions panel for immediate operations.",
    result: "Operational ERP streamlining daily business processes.",
    responsibilities: ["Full-stack development"],
  },
  {
    slug: "it-fest-6",
    title: "IT-Fest 6.0 — Universitas Paramadina",
    category: "Frontend",
    description: "Event platform for IT-Fest 6.0 — competition registration, participant management, and jury scoring.",
    longDescription: "Flagship technology festival featuring competitions, talk shows, expos, and games under the theme 'Human-Centered AI: Transforming the World with Integrity'.",
    tech: ["Next.js", "Tailwind CSS"],
    year: "2024",
    role: "Frontend Developer",
    image: "/porto/it-fest.png",
    images: ["/porto/it-fest.png"],
    color: "#0B5FFF",
    challenge: "Competition registration and festival promotion require a vibrant yet highly usable flow.",
    goal: "Create a festive landing that drives registrations while clearly communicating the event lineup.",
    process: ["Pop-art hero concept", "Competition and event flow", "Jury and scoring interface"],
    solution: "Blue hero with pink 'IT FEST 6.0' burst, 'Daftar Sekarang' CTA, and colorful program sections.",
    result: "Live event website supporting hundreds of participants.",
    responsibilities: ["Next.js development", "Pop-art UI execution"],
  },
  {
    slug: "bengkel-it",
    title: "Bengkel IT — Next.js",
    category: "Frontend",
    description: "Professional IT service landing — laptop repair, RAM upgrades, and on-site support with warranty.",
    longDescription: "Service landing that uses floating service pills to convey speed, professionalism, and full warranty coverage.",
    tech: ["Next.js", "Tailwind CSS"],
    year: "2024",
    role: "Frontend Developer",
    image: "/porto/bengkel-it.png",
    images: ["/porto/bengkel-it.png"],
    color: "#0DBA6A",
    challenge: "An IT workshop must earn trust within five seconds of arrival.",
    goal: "Showcase services, warranty, and speed in a single, compelling hero.",
    process: ["Floating service pill system", "Hero and CTA composition", "Trust and credibility layer"],
    solution: "Hero headline 'Solusi IT yang Tuntas & Terpercaya' with floating pills for Laptop Repair, RAM Upgrade, and more.",
    result: "High-converting landing page for the IT service business.",
    responsibilities: ["Frontend development"],
  },
  {
    slug: "edukasi-berhenti-merokok",
    title: "Edukasi Berhenti Merokok — Laravel",
    category: "Frontend",
    description: "Quit-smoking education platform — progress tracking, learning modules, and community support.",
    longDescription: "User home 'Selamat datang, Andika' — 6 active learning materials, 3 verified milestones, and 6 forum discussions to build smoke-free habits.",
    tech: ["Laravel", "MySQL"],
    year: "2024",
    role: "Frontend Developer",
    image: "/porto/edukasiberhentimerokok.png",
    images: ["/porto/edukasiberhentimerokok.png"],
    color: "#0F3D2E",
    challenge: "Smoking cessation requires gradual support, not lecturing.",
    goal: "Provide a supportive space that tracks progress, educates, and connects a community.",
    process: ["Progress tracker design", "Learning content and forum", "Consultation flow"],
    solution: "'3 Verified' milestone card with e-books, forums, and calls to action like 'Lihat Progress' and 'Cari Konsultasi'.",
    result: "Active education platform supporting behavior change.",
    responsibilities: ["Laravel development", "UI implementation"],
  },
];

export const categories = ["All", "Mobile", "UI/UX", "Frontend", "Full Stack", "Web3"] as const;
export type CategoryFilter = typeof categories[number];
